### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by kostia-lev** [icarus-sullivan/react-calendar-material#1]
Getting 'SyntaxError: import declarations may only appear at top level of a module' after I try to launch this calendar in create react app

//index.js
import React from 'react';
import ReactDOM from 'react-dom';
//import App from './App';
import './index.css';
import Calendar from 'react-calendar-material';

ReactDOM.render(
    <Calendar
        accentColor={'blue'}
        orientation={'flex-col'}
        showHeader={false}
        onDatePicked={(d) => {
            console.log('onDatePicked', d);
        }}/>,
  document.getElementById('root')
);

**Comment by icarus-sullivan** [comment]
Is this code in the index.js file or App.js file??

Create-react-app uses index.js as it's injection point so you might need to move your logic there. If it's something else I will have to take a look at it tonight. 

Thanks

**Comment by kostia-lev** [comment]
The code is in index.js file

SyntaxError: import declarations may only appear at top level of a module  bundle.js:32503:1

**Comment by icarus-sullivan** [comment]
Sorry it took a day longer to get back to you. I had some heavy stuff come up and wasn't able to check until today. 

The error you are seeing is due to babel not being configure correctly. I've added bable-preset-es2015 and it should work now. Apologies for any inconvenience.
